In [2]:
from google.colab import drive

drive.mount('/content/drive/')

Mounted at /content/drive/

In [3]:
import os

path = '/content/drive/My Drive/Practise_files/'

os.listdir(path)

['Customers.csv',
 'sample.txt',
 'sample.json',
 'Flavors.csv',
 'LOTR.csv',
 'LOTR 2.csv',
 'Ice Cream Ratings.csv',
 'Customer Call List.xlsx',
 'world_population.csv',
 'customer_shopping_behavior.csv']

In [4]:
import pandas as pd

df = pd.read_csv('/content/drive/My Drive/Practise_files/customer_shopping_behavior.csv')

df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [8]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [11]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [ ]:
df.isnull().sum()

In [18]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')
df = df.rename(columns = {'purchase_amount_(usd)' : 'purchase_amount'})

In [19]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [20]:
# Create new column Age group

labels = ['Young Adult', 'Adult', 'Middle-aged', 'Senior']
df['Age_group'] = pd.qcut(df['age'], q = 4, labels=labels)

In [21]:
df[['age', 'Age_group']]

      age    Age_group
0      55  Middle-aged
1      19  Young Adult
2      50  Middle-aged
3      21  Young Adult
4      45  Middle-aged
...   ...          ...
3895   40        Adult
3896   52  Middle-aged
3897   46  Middle-aged
3898   44        Adult
3899   52  Middle-aged

[3900 rows x 2 columns]

In [30]:
# create column purchase frquency days

frequency_mapping = {
    "Fortnightly" : 14,
    "Weekly" : 7,
    "Monthly" : 30,
    "Quarterly" : 90,
    "Bi-Weekly" : 14,
    "Annually" : 365,
    "Every 3 Months" : 90
}

df['Purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [31]:
df[['frequency_of_purchases', 'Purchase_frequency_days']].drop_duplicates() #see all unique pairs

   frequency_of_purchases  Purchase_frequency_days
0             Fortnightly                       14
2                  Weekly                        7
4                Annually                      365
6               Quarterly                       90
10              Bi-Weekly                       14
15                Monthly                       30
20         Every 3 Months                       90

In [33]:
df[['discount_applied', 'promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [34]:
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [35]:
df = df.drop(columns='promo_code_used')

In [38]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'Age_group', 'Purchase_frequency_days'],
      dtype='object')